#!/usr/bin/env bun

import { compile, compileFromFile } from "json-schema-to-typescript";
import $RefParser from "@apidevtools/json-schema-ref-parser";
import { glob, globSync, globStream, globStreamSync, Glob } from "glob";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import mergeAllOf from "json-schema-merge-allof";

const journalEntryPoints = await glob("schema/schemas/*/*.json");

console.log("clean up output directory");

const generatedRoot = join(process.cwd(), "src", "generated");

await rm(generatedRoot, {
  recursive: true,
  force: true,
});
await mkdir(generatedRoot, { recursive: true });

const barrelFileContents: string[] = [
  `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */`,
];
const eventNames: string[] = [];

for (const schemaPath of journalEntryPoints) {
  console.info(basename(join(schemaPath, "..")));
  if (basename(join(schemaPath, "..")) === "common") {
    continue;
  }
  // We first use @apidevtools/json-schema-ref-parser to inline any external refs.
  // json-schema-to-typescript gets a bit icky with the way the Schemas are structured.
  const schema = await $RefParser.dereference(schemaPath);
  // extends is deprecated, and the data was inlined by RefParser.dereference into the allOf
  // it's still in the Schema for backwards compatibility, although its not really valid per JSON Schema Spec.
  delete (schema as any).extends;

  // Jixxed's Schema uses inheritance and defines the `event` field to be just any string
  // We can do better by making the events essentially be tagged unions.
  // We define the event field to be a literal, so one can just e.g.
  // obj.event === "Loadout" and TS knows we have a Loadout event using the Loadout structure
  const name = basename(schemaPath, ".json");
  const allOfIds = (schema.allOf ?? []).findIndex((e) => e.title === "Event");
  if (allOfIds >= 0) {
    (schema as any).allOf[allOfIds].properties.event.const = name;
    delete (schema as any).allOf[allOfIds].properties.event.examples;
    delete (schema as any).allOf[allOfIds].properties.event.type;
  }
  const result =
    (
      await compile(schema as any, `${name}Event`, {
        format: true,
      })
    ).replaceAll("export ", "") + `\n\nexport default ${name}Event;`;
  await writeFile(join(generatedRoot, `${name}.ts`), result);
  barrelFileContents.push(`import ${name}Event from './${name}.js'`);
  eventNames.push(name + "Event");
}

// at the end, create a barrel file
barrelFileContents.push(
  `export type JournalEvent = `,
  ...eventNames.map((e) => `| ${e}`),
);

await writeFile(join(generatedRoot, "index.ts"), barrelFileContents.join("\n"));
